version: "0.2"
ignorePaths:
  - .gitignore
  - .dockerignore
  - requirements.txt
  - builds*
allowCompoundWords: true
dictionaries:
  - python
words:
  - anyio
  - asgi
  - Buildx
  - httpx
  - isort
  - Misha
  - mypy
  - pydantic
  - pytest
  - starlette
  - uvicorn
  - vybornyy
ignoreWords: []
import: []
enableFiletypes:
  - dockercompose
  - ini
  - makefile
  - markdown
  - toml
